### ISSUE TITLE
meta-data in content.opf

### ISSUE THREAD

**Issue by michael-77** [b-t-k/william-carlos-williams_poetry#3]
Should `producer-2` be "L. A. Vermeer" or indeed "Leslie A. Vermeer" rather than "LA Vermeer" without any full stops?

**Comment by b-t-k** [comment]
Being a modernist, as an affectation, she has done away with the periods in her personal identity. I reproduced it that way as it is consistent.

**Comment by michael-77** [comment]
:-)
