### ISSUE TITLE
Missing frontmatter

### ISSUE THREAD

**Issue by michael-77** [b-t-k/william-carlos-williams_poetry#6]
Missing front-matter. I'm not sure how to deal with this @acabal. 

Each of the 'volumes' is a published antholgy and in the page scans (and in the gutenberg transcription) each of those volumes has frontmatter - two of them have a dedication and one of them has an unusual epigraph in (bad) Spanish? 

Is there a way to recognise the frontmatter correctly when we are combining the anthologies into a single collection as it seems a shame to just drop all the frontmatter completely.

**Comment by b-t-k** [comment]
If @acabal has no opinion, we will leave as is. Leslie wants to do one more pass to doublecheck the head hierarchy in a build and then I will post to the group when its good to go.

**Comment by michael-77** [comment]
It's been less than 24 hours - give him a chance ;-)

**Comment by b-t-k** [comment]
:-)

It'll be a bit before L gets to it anyway.

**Comment by acabal** [comment]
Sure. The volumes are already included in the work so just include the frontmatter in the appropriate places. They would be new `<section>`s at the top level of each volume.

**Comment by acabal** [comment]
I guess it's a little late in the game to ask about this, but are there any duplicate poems in the 3 poetry books WCW has on PG? If not and each book is unique then maybe we can just produce them separately after all. I can take care of that Bruce if you don't want to work on this any more; we would just remove one of the volumes from this, change the title, and pop the cut volume into a separate production. `create-draft` can do the heavy lifting. I'm just thinking that if we include the frontmatter it would be a little confusing to see these as separate books in one volume, but as Michael says it would be a shame to lose the frontmatter.

**Comment by b-t-k** [comment]
:-) We did have this discussion before I started: https://groups.google.com/forum/#!topic/standardebooks/EfQ1KK62vlA

But if you want to split them back up then we can do that. The Tempers is really short though.

**Comment by acabal** [comment]
Yeah I remember, I'm just waffling. If we split this up it would be inconsistent with our TS Eliot collection. Though we could always split that up too. Let's proceed as discussed. This is something I can go back and do myself if my thinking crystallizes more in the future.

**Comment by b-t-k** [comment]
To be clear. We will just add the frontmatter and leave as one volume?

**Comment by acabal** [comment]
Yeah

**Comment by b-t-k** [comment]
Great. I will work on that and give it back to Leslie to do a final proof and we should be good to .

**Comment by michael-77** [comment]
Sounds good 😀
