### ISSUE TITLE
Review subtitles in poetry-2.xhtml

### ISSUE THREAD

**Issue by michael-77** [b-t-k/william-carlos-williams_poetry#8]
In particular, review the use of `<span epub:type="subtitle">`. 

The first use of `<span epub:type="subtitle">` is for a dedication which is really a `z3998:dedication` and targeted in that way rather than with `<em>`. 

The second is for "Suite" which in the page scans has the same prominence as the sub-chapter headings in the poem "The Wanderer" - "Advent" etc. 

The last does seem to be a subtitle and should be targeted directly in css rather than being set in `<em>`.  

https://github.com/standardebooks/wilfred-owen_poetry/blob/efef6f29280c7eac3442b3af6bb2a2e6990d110c/src/epub/text/poetry.xhtml#L251 gives an example of how to use `<header>` to contain these sort of things.

**Comment by b-t-k** [comment]
I will admit to being confused by this particular bit of coding.  
Do I leave the dedication as a part of the h3 like it is now? 

If I bump Suite down to h4 then that puts the Roman numeral sections down to h5. I have also seen it as _January Morning (Suite)_ How about I try it as h4 class="subhead" but leave the Romans as h4  as well and use the css to left justify it.

**Comment by b-t-k** [comment]
Ok having done that I now realize the h3 are centered so I could just leave it as a regular h4. But should the roman numerals bump down to h5?

**Comment by michael-77** [comment]
So for the first one:
```
<article id="conquest" epub:type="z3998:poem">
	<header>
		<h3 epub:type="title">Conquest</h3>
		<p epub:type="z3998:dedication">Dedicated to <abbr class="name eoc">F. W.</abbr></p>
	</header>
```
You can target dedications with `[epub|type~="z3998:dedication"]` in `local.css`. Do also note the extra `eoc` class in there.

It sounds like the second one may be a subtitle given that you've seen it as such elsewhere so you could probably leave it alone.

The third one:
```
<article id="the-wanderer" epub:type="z3998:poem">
	<h3 epub:type="title">
		<span>The Wanderer</span>
		<span epub:type="subtitle">A Rococo Study</span>
	</h3>
```
You can target the subtitles for specific styling in `local.css` using `#january-morning [epub|type~="subtitle"]` and `#the-wanderer [epub|type~="subtitle"]` to get them to look the way you want but I suspect that it will be an editorial decision rather than poetical so styling them using a global style could work best. Appreciate that you've done the research on it though.

**Comment by b-t-k** [comment]
I reworked the dedication as you suggested. I am having a hard time getting it to center though. No idea why—can you take a look?

 In the end I decided for the subtitles, that the way it was done in Keats is probably the best model for both which is basically what you suggested:
https://github.com/standardebooks/john-keats_poetry/blob/d4f92c9e9ac3dff5157ccc0c3c766a94a676e3b7/src/epub/text/poetry.xhtml#L1185

**Comment by michael-77** [comment]
Try 
```
[epub|type~="z3998:poem"] [epub|type~="z3998:dedication"]{
	text-align: center;
}
```
for the alignment. You'll need to play about for the spacing.

The issue is that the css declaration `[epub|type~="z3998:poem"] p` has a higher specificity in css than just `[epub|type~="z3998:dedication"]` and that's why the left alignment was sticking!
